import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import TanStack from 'app/components/Providers/TanStack'
import { GoogleTagManager } from '@next/third-parties/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const idTagManager = process.env.ANALYTICS_ID || ''

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Head>
        <GoogleTagManager gtmId={idTagManager} />
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${idTagManager}`}
            height='0'
            width='0'
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>
      </Head>
      <body className={inter.className}>
        <TanStack>{children}</TanStack>
      </body>
    </html>
  )
}
